// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhrptvFNrMwyidanAPjPnNGPiJ9HuU4o',
    appId: '1:679640573288:web:b0b05c9b2654ec77c222dd',
    messagingSenderId: '679640573288',
    projectId: 'parksahay',
    authDomain: 'parksahay.firebaseapp.com',
    storageBucket: 'parksahay.firebasestorage.app',
    measurementId: 'G-XHE7EVEL29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxowIfRz3a8fKuYF8D6QX4IblYoUP3VHI',
    appId: '1:679640573288:android:dffd14a734645383c222dd',
    messagingSenderId: '679640573288',
    projectId: 'parksahay',
    storageBucket: 'parksahay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBiV2VuFTnGC8nktpF6w6KdCbPby7b63M',
    appId: '1:679640573288:ios:9c559442f286f006c222dd',
    messagingSenderId: '679640573288',
    projectId: 'parksahay',
    storageBucket: 'parksahay.firebasestorage.app',
    iosBundleId: 'com.example.parksahay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBiV2VuFTnGC8nktpF6w6KdCbPby7b63M',
    appId: '1:679640573288:ios:9c559442f286f006c222dd',
    messagingSenderId: '679640573288',
    projectId: 'parksahay',
    storageBucket: 'parksahay.firebasestorage.app',
    iosBundleId: 'com.example.parksahay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJhrptvFNrMwyidanAPjPnNGPiJ9HuU4o',
    appId: '1:679640573288:web:d7066effcf6d89c2c222dd',
    messagingSenderId: '679640573288',
    projectId: 'parksahay',
    authDomain: 'parksahay.firebaseapp.com',
    storageBucket: 'parksahay.firebasestorage.app',
    measurementId: 'G-J89XJ82JCL',
  );
}
